#!/bin/sh
# TWITTER Application CONF
export AG_consumerKey="XXXXXXXXXXXXXXXXXXXXXXXXX"
export AG_consumerSecret="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
export AG_accessToken="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
export AG_accessTokenSecret="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxx"
export AG_sinceId=1
